---
all:
  vars:
    ansible_ssh_user: isucon
    ansible_python_interpreter: /usr/bin/python3
    # TODO: インスタンスに接続するための秘密鍵を指定する
    # ansible_ssh_private_key_file: ~/.ssh/isucon
  hosts:
    # TODO: インスタンスのIPアドレスを指定する
    instance1:
      ansible_host: 13.230.176.152
    # instance2:
    #   ansible_host: 54.238.176.70
    # instance3:
    #   ansible_host: 13.114.121.220
