---
- name: copy mysql.cnf
  copy:
    src: ../../etc/mysql/mysqld.cnf
    dest: /etc/mysql/mysql.cnf
    mode: 0644

- name: change file ownership /var/log/mysql/mysql-slow.log
  file:
    path: /var/log/mysql/mysql-slow.log
    owner: mysql
    group: adm
    mode: 0644

- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes
