---
- name: create .ssh directory
  file:
    path: /home/isucon/.ssh
    state: directory

- name: get public key
  shell: |
    # TODO: チーム全員の公開鍵を取得するようにする
    # 例: https://github.com/{yoRyuuuuu,user2,user3}.keys
    # ブラウザからは取得できないが、curlコマンドで取得できる
    # url: https://github.com/yoRyuuuuu.keys
    curl https://github.com/yoRyuuuuu.keys >> /home/isucon/.ssh/authorized_keys

- name: change owner
  file:
    path: /home/isucon/.ssh
    owner: isucon
    group: isucon
    recurse: yes

- name: change permission of authorized_keys
  file:
    path: /home/isucon/.ssh/authorized_keys
    mode: 0644
